### ISSUE TITLE
Some lines are not cut

### ISSUE THREAD

**Issue by fa-bien** [kallaballa/ctrl-cut#115]
What happens: some lines disappear between the .cut and the .raw. At least that's what I think: they are in the .cut but not in the preview from ctrl-cut.

attached an archive with 3 files:

blankpuzzle.pdf: the input file I want to use for cutting
cut.cut: the file saved by ctrl-cut
bug.raw: the cut in raw format

[missing_lines.zip](https://github.com/kallaballa/ctrl-cut/files/57391/missing_lines.zip)

**Comment by fa-bien** [comment]
Note: after a bit of searching it appears the issue is in cut/operations/Deonion.cpp on lines 74 and 75. Commenting these lines works, *but* then I it could be that some lines are drawn twice. My limited understanding is that as soon as a segment has been walked through, both points from this segment are removed. It is however not always valid to do so (see example above). So a point should only be removed if it does not belong to any other edge that hasn't been walked through yet. I am not familiar enough with the code to make that change though.

**Comment by kallaballa** [comment]
thx for you efforts! tests show that you hit the nail.
